//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PM2016.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PM2016.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   프로세서 선호도과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string textAffinity {
            get {
                return ResourceManager.GetString("textAffinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   해당 프로세스를 실행할 수 있는 프로세서과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string textAffinityWindowMain {
            get {
                return ResourceManager.GetString("textAffinityWindowMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   취소과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string textCancel {
            get {
                return ResourceManager.GetString("textCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CPU과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string textCPU {
            get {
                return ResourceManager.GetString("textCPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CPU 사용률과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string textCpuUsage {
            get {
                return ResourceManager.GetString("textCpuUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   개과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string textGae {
            get {
                return ResourceManager.GetString("textGae", resourceCulture);
            }
        }
        
        /// <summary>
        ///   작업 끝내기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string textKillProcess {
            get {
                return ResourceManager.GetString("textKillProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   메모리과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string textListMem {
            get {
                return ResourceManager.GetString("textListMem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이름과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string textListName {
            get {
                return ResourceManager.GetString("textListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string textListPID {
            get {
                return ResourceManager.GetString("textListPID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   메모리 사용률과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string textMemUsage {
            get {
                return ResourceManager.GetString("textMemUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///    프로세스가 존재하지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string textNotExist {
            get {
                return ResourceManager.GetString("textNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   확인과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string textOK {
            get {
                return ResourceManager.GetString("textOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AboveNormal과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string textPriorityAbovenormal {
            get {
                return ResourceManager.GetString("textPriorityAbovenormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BelowNormal과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string textPriorityBelownormal {
            get {
                return ResourceManager.GetString("textPriorityBelownormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   High과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string textPriorityHigh {
            get {
                return ResourceManager.GetString("textPriorityHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Idle과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string textPriorityIdle {
            get {
                return ResourceManager.GetString("textPriorityIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Normal과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string textPriorityNormal {
            get {
                return ResourceManager.GetString("textPriorityNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RealTime과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string textPriorityRealtime {
            get {
                return ResourceManager.GetString("textPriorityRealtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   프로세스과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string textProcess {
            get {
                return ResourceManager.GetString("textProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///    프로세스를 종료합니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string textProcessKill {
            get {
                return ResourceManager.GetString("textProcessKill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   선호도 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string textSetAffinity {
            get {
                return ResourceManager.GetString("textSetAffinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   우선순위 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string textSetPriority {
            get {
                return ResourceManager.GetString("textSetPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   알림과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string textWarning {
            get {
                return ResourceManager.GetString("textWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모든 프로세서과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string textWholeProcessor {
            get {
                return ResourceManager.GetString("textWholeProcessor", resourceCulture);
            }
        }
    }
}
